#!/usr/bin/env julia
# playground.jl — Indexes the Modelica Standard Library and runs example queries
# using the GitHub Models free embedding API (150 requests/day, no billing setup).
#
# Usage:
#   export GITHUB_TOKEN=github_pat_...
#   julia --project playground.jl
#   julia --project playground.jl /path/to/Modelica/library

using ModelicaRag
import ModelicaRag.Store: open_store, search_chunks, lookup_symbol, fuzzy_lookup, chunk_count
import ModelicaRag.Embedder: embed, GithubModelsEmbedder

const PROJECT_DIR = dirname(abspath(@__FILE__))

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

function sep(title::String = "")
    if isempty(title)
        println("\n" * "─"^60)
    else
        pad = max(1, 57 - length(title))
        println("\n─── $title " * "─"^pad)
    end
end

# ---------------------------------------------------------------------------
# Banner
# ---------------------------------------------------------------------------

println("="^60)
println("  ModelicaRag Playground")
println("  GitHub Models free tier — 150 requests/day, no billing")
println("="^60)
println()

# ---------------------------------------------------------------------------
# Prerequisites
# ---------------------------------------------------------------------------

token = get(ENV, "GITHUB_TOKEN", "")
if isempty(token)
    println(stderr, "ERROR: GITHUB_TOKEN is not set.")
    println(stderr, "  export GITHUB_TOKEN=github_pat_...")
    exit(1)
end
println("GITHUB_TOKEN detected.")

# ---------------------------------------------------------------------------
# Locate the Modelica Standard Library
# ---------------------------------------------------------------------------

function find_msl()
    # Devcontainer: postCreate.sh clones the MSL repo here.
    devcontainer_path = joinpath(PROJECT_DIR, "data", "msl", "Modelica")
    isdir(devcontainer_path) && return devcontainer_path

    # Repo-local parser fixture: enough to exercise the playground offline.
    models_path = joinpath(PROJECT_DIR, "Models")
    isfile(joinpath(models_path, "msl.mo")) && return models_path

    # Local OpenModelica installations.
    for root in [get(ENV, "OPENMODELICAHOME", ""),
                 "/usr/share/openmodelica/libraries",
                 "/usr/lib/omlibrary",
                 "/usr/local/lib/omlibrary",
                 expanduser("~/.openmodelica/libraries")]
        isdir(root) || continue
        # Sort descending so newer versions (e.g. "Modelica 4.0.0") come first.
        for entry in sort(readdir(root); rev = true)
            startswith(entry, "Modelica") && isdir(joinpath(root, entry)) &&
                return joinpath(root, entry)
        end
    end
    return ""
end

msl_path = length(ARGS) >= 1 ? ARGS[1] : find_msl()

if isempty(msl_path) || !isdir(msl_path)
    println(stderr, "ERROR: Modelica Standard Library not found.")
    println(stderr, "  Pass the path as an argument:")
    println(stderr, "    julia --project playground.jl /path/to/Modelica/library")
    exit(1)
end

println("Modelica library: $msl_path")
println()

# ---------------------------------------------------------------------------
# Write a self-contained playground config
# ---------------------------------------------------------------------------
# Stored in data/ which is gitignored, so it never conflicts with config.toml.

config_path = joinpath(PROJECT_DIR, "data", "playground.config.toml")
db_path     = joinpath(PROJECT_DIR, "data", "playground.db")
mkpath(dirname(config_path))

open(config_path, "w") do io
    println(io, "# Auto-generated by playground.jl — do not edit manually.")
    println(io, "[embeddings]")
    println(io, "backend    = \"github_models\"")
    println(io, "model      = \"text-embedding-3-small\"")
    println(io, "batch_size = 32")
    println(io, "[store]")
    println(io, "path = \"$db_path\"")
    println(io, "[codebase]")
    println(io, "root       = \"$msl_path\"")
    println(io, "extensions = [\".mo\"]")
end

# ---------------------------------------------------------------------------
# Index
# ---------------------------------------------------------------------------

println("Indexing library (incremental — only changed files are re-embedded).")
println("First run uses API requests proportional to the number of .mo files.")
if msl_path == joinpath(PROJECT_DIR, "Models")
    println("Using the repo-local MSL parser fixture in ./Models.")
end
println()

ModelicaRag.main(["index", "--config", config_path])

# ---------------------------------------------------------------------------
# Open store + embedder for the demo queries
# ---------------------------------------------------------------------------

db       = open_store(db_path)
embedder = GithubModelsEmbedder(; token, model = "text-embedding-3-small")
n        = chunk_count(db)

println()
println("Index ready: $n chunks.")

# ---------------------------------------------------------------------------
# Demo queries
# ---------------------------------------------------------------------------

println()
println("Running demo queries.")
println("Semantic searches use one API request each.")
println("Lookup and fuzzy queries are local only (no API call).")

function demo_search(label::String, query::String; top_k::Int = 4)
    sep("Semantic — $label")
    println("Query: \"$query\"")
    println()
    vec     = embed(embedder, query)
    results = search_chunks(db, vec, top_k)
    if isempty(results)
        println("  No results.")
        return
    end
    for (i, r) in enumerate(results)
        c = r.chunk
        println("  $i.  sim=$(round(r.similarity; digits=3))  $(c.symbol_type)  $(c.symbol_name)")
        println("       $(c.file_path):$(c.start_line)")
    end
end

function demo_lookup(name::String)
    sep("Exact lookup — \"$name\"")
    results = lookup_symbol(db, name)
    if isempty(results)
        println("  Not found.")
        return
    end
    for c in results
        println("  $(c.symbol_type)  $(c.symbol_name)")
        println("  $(c.file_path):$(c.start_line)-$(c.end_line)")
    end
end

function demo_fuzzy(pattern::String; top_k::Int = 8)
    sep("Fuzzy name — \"$pattern\"")
    results = fuzzy_lookup(db, pattern, top_k)
    if isempty(results)
        println("  No matches.")
        return
    end
    for c in results
        println("  $(c.symbol_type)  $(c.symbol_name)")
    end
end

# Semantic searches — each costs one API request against the free tier.
demo_search("thermal resistance",      "thermal resistance between two heat ports")
demo_search("ideal voltage source",    "ideal voltage source with fixed voltage")
demo_search("PID controller",          "PID controller with integrator and derivative term")
demo_search("state machine transition","state machine with guarded transition trigger")

# Exact lookups — resolved from the SQLite index, no API call.
demo_lookup("Modelica.Math.sin")
demo_lookup("Modelica.Electrical.Analog.Basic.Resistor")

# Fuzzy name searches — SQL LIKE query, no API call.
demo_fuzzy("HeatTransfer")
demo_fuzzy("Sensor")
demo_fuzzy("Controller")

sep()
println()
println("="^60)
println("  Done. 4 API requests used (the 4 semantic searches).")
println("  Lookup and fuzzy queries are free — local SQLite only.")
println("  The index at data/playground.db is reused on subsequent runs.")
println("="^60)
println()
